# Generated by Django 4.2.10 on 2024-07-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_photo_dislikes_count_photo_likes_count_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
