# Generated by Django 4.2.10 on 2024-07-26 13:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_like_dislike_alter_like_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
